export const LOAD_USERPOST_REQUEST = 'LOAD_USERPOST_REQUEST';
export const LOAD_USERPOST_SUCCESS = 'LOAD_USERPOST_SUCCESS';
export const LOAD_USERPOST_FAILURE = 'LOAD_USERPOST_FAILURE';

export const LOAD_USERSEARCH_REQUEST = 'LOAD_USERSEARCH_REQUEST';
export const LOAD_USERSEARCH_SUCCESS = 'LOAD_USERSEARCH_SUCCESS';
export const LOAD_USERSEARCH_FAILURE = 'LOAD_USERSEARCH_FAILURE';
